name: app
description: Advaya FM NaipuNya - Sovereign Engine
publish_to: 'none'
version: 1.0.0+1006
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  permission_handler: ^11.3.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/webxr/
    - assets/webxr/assets/
